# Substitution variables, defined in Google Cloud Builder "Hello World Build Staging" trigger:
#
# _KMS_KEYRING
# _KMS_KEY

steps:
  # Build container image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/hello-world-gcb:${SHORT_SHA}'
      - '.'
  
  # Retrieve and decrypt the GitHub Hub configuration, contains GitHub username + token
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gsutil cp gs://${PROJECT_ID}-gitops-hello-world-configs/hub.enc hub.enc
        gcloud kms decrypt \
          --ciphertext-file hub.enc \
          --plaintext-file /config/hub \
          --location global \
          --keyring ${_KMS_KEYRING} \
          --key ${_KMS_KEY}
    volumes:
      - name: 'config'
        path: /config

images:
  - 'gcr.io/${PROJECT_ID}/hello-world-gcb:${SHORT_SHA}'